sign up spec
running into application code error due to recaptcha.. This is due to recaptcha security plugin preventing spam
(uncaught exception)
ReferenceError: grecaptcha is not defined